version: '3.3'

# servicios a ejecutar
services:

# MySQL con nombre `cyclenet-db`
  db:
    image: mysql:8.0.31
    container_name: cyclenet-db
    environment:
    - MYSQL_DATABASE=cyclenet
    - MYSQL_USER=cyclenet
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWORD=secret
    ports:
    - '3306:3306'
    expose:
    - '3306'